### ISSUE TITLE
Tests suites never fail

### ISSUE THREAD

**Issue by NicolasPetton** [ecukes/ecukes#170]
#### How to reproduce?

- Setup a project following the installation steps in the README
- Create a feature that should fail
- Run `cask`
- Run `cask exec ecukes`
- Result:

```
.

1 scenarios (0 failed, 1 passed)
2 steps (0 failed, 0 skipped, 2 passed)
```

#### Expected result

The test should be failing

#### Additional information
- Emacs 25.3 from Fedora 26

**Comment by DamienCassou** [comment]
I can reproduce the problem.

**Comment by davidshepherd7** [comment]
Hi, yeah this is caused by an issue with espuds. A fix has been released but it hasn't made it to stable yet because I wanted to wait ontil the travis tests were working (they're broken due to an issue with cask). Still waiting on a code review for the travis fix unfortunately.

I might just merge it unreviewed because at this point the damage being caused by the existing bug is probably worse than anything I could cause with the fix...

**Comment by davidshepherd7** [comment]
But yeah one workaround is to use melpa unstable for now, or if you find the issue I opened elsewhere you can use a monkey patch to fix the bug in cl-assert which is the root cause of this whole mess.

**Comment by NicolasPetton** [comment]
@davidshepherd7 Thanks for the explanations.

I'm using melpa, not melpa-stable, and I have the issue.

```
(source melpa)

  (depends-on "ecukes")
  (depends-on "espuds"))
```

I just removed `.cask` and ran `$ cask` again, I still have the same problem.

**Comment by DamienCassou** [comment]
@davidshepherd7 which travis fix do you expect to get a review on? To fix my problems with Cask, I follow: https://github.com/cask/cask/issues/399#issuecomment-331640427. See for example https://github.com/DamienCassou/hierarchy/blob/master/.travis.yml#L6.

**Comment by davidshepherd7** [comment]
@DamienCassou Yeah that's the one, my PR is here: https://github.com/cask/cask/pull/404

@NicolasPetton Hmm, I'll have to look into it again tonight then. For now you can try [this](https://github.com/davidshepherd7/espuds/commit/07a479a8ecb39e5f0b7342f7951257572809bcba) which is what I've been using as a work around.

**Comment by DamienCassou** [comment]
https://github.com/ecukes/espuds/pull/45#issuecomment-342113168

**Comment by davidshepherd7** [comment]
It turns out I'd only added the workaround for emacs 25.2 because I expected the bug to be fixed in 25.3, but 25.3 was a security hotfix so it wasn't. 

Thanks for reporting it, should be fixed now :+1:

**Comment by NicolasPetton** [comment]
David Shepherd <notifications@github.com> writes:

> It turns out I'd only added the workaround for emacs 25.2 because I
> expected the bug to be fixed in 25.3, but 25.3 was a security hotfix
> so it wasn't.

Indeed, we'll have to wait for 26.1 (which is just around the corner now).

> Thanks for reporting it, should be fixed now :+1:

Awesome, thank you!
